-- =============================================================================
-- V007: Create desafios table
-- =============================================================================
-- Creates the desafios (technical challenges) table
-- Based on product/DATABASE.md §3.4
-- =============================================================================

CREATE TABLE desafios (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  creador_usuario_id  UUID NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  organizacion_id     UUID REFERENCES organizaciones(id) ON DELETE RESTRICT,
  prompt_version_id   UUID NOT NULL REFERENCES prompt_versiones(id) ON DELETE RESTRICT,
  titulo              VARCHAR(200) NOT NULL,
  enunciado           TEXT NOT NULL,
  rubrica_oculta      JSONB NOT NULL,
  contexto_origen     VARCHAR(20) NOT NULL,
  tecnologia          VARCHAR(100) NOT NULL,
  seniority           VARCHAR(20) NOT NULL,
  minutos_estimados   INTEGER NOT NULL DEFAULT 60,
  es_publico          BOOLEAN NOT NULL DEFAULT FALSE,
  estado              VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  CONSTRAINT chk_desafio_contexto CHECK (contexto_origen IN ('CORPORATIVO', 'ACADEMICO', 'BIBLIOTECA')),
  CONSTRAINT chk_desafio_seniority CHECK (seniority IN ('TRAINEE', 'JR', 'SSR', 'SR', 'LEAD')),
  CONSTRAINT chk_desafio_estado CHECK (estado IN ('BORRADOR', 'REVISION', 'ACTIVO', 'ARCHIVADO')),
  CONSTRAINT chk_desafio_minutos CHECK (minutos_estimados > 0 AND minutos_estimados <= 480)
);

-- Indexes for common queries
CREATE INDEX idx_desafios_creador ON desafios(creador_usuario_id);
CREATE INDEX idx_desafios_organizacion ON desafios(organizacion_id) WHERE organizacion_id IS NOT NULL;
CREATE INDEX idx_desafios_publicos ON desafios(es_publico, estado) WHERE es_publico = TRUE AND estado = 'ACTIVO';
CREATE INDEX idx_desafios_tecnologia ON desafios(tecnologia, seniority);
CREATE INDEX idx_desafios_rubrica_gin ON desafios USING GIN (rubrica_oculta);

-- Trigger to automatically update updated_at
CREATE TRIGGER trg_desafios_updated_at
  BEFORE UPDATE ON desafios
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE desafios IS 'Technical challenges generated by LLM';
COMMENT ON COLUMN desafios.id IS 'UUID primary key';
COMMENT ON COLUMN desafios.creador_usuario_id IS 'User who created the challenge';
COMMENT ON COLUMN desafios.organizacion_id IS 'Organization (null for public library challenges)';
COMMENT ON COLUMN desafios.prompt_version_id IS 'Prompt version used to generate this challenge';
COMMENT ON COLUMN desafios.titulo IS 'Challenge title';
COMMENT ON COLUMN desafios.enunciado IS 'Challenge statement/description';
COMMENT ON COLUMN desafios.rubrica_oculta IS 'Hidden evaluation rubric (JSONB)';
COMMENT ON COLUMN desafios.contexto_origen IS 'Origin context: CORPORATIVO, ACADEMICO, BIBLIOTECA';
COMMENT ON COLUMN desafios.tecnologia IS 'Technology/language';
COMMENT ON COLUMN desafios.seniority IS 'Target seniority level';
COMMENT ON COLUMN desafios.minutos_estimados IS 'Estimated time in minutes';
COMMENT ON COLUMN desafios.es_publico IS 'Whether challenge is public in library';
COMMENT ON COLUMN desafios.estado IS 'Status: BORRADOR, REVISION, ACTIVO, ARCHIVADO';

-- Log successful creation
DO $$
BEGIN
  RAISE NOTICE 'Table desafios created successfully';
END $$;

-- Made with Bob