package com.talentpool.domain;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Desafio entity - Technical challenge generated by LLM.
 *
 * <p>Based on product/DATABASE.md §3.4
 */
@Entity
@Table(name = "desafios")
public class Desafio extends PanacheEntityBase {

  @Id
  @Column(columnDefinition = "UUID")
  public UUID id;

  @Column(name = "creador_usuario_id", nullable = false, columnDefinition = "UUID")
  public UUID creadorUsuarioId;

  @Column(name = "organizacion_id", columnDefinition = "UUID")
  public UUID organizacionId;

  @Column(name = "prompt_version_id", nullable = false, columnDefinition = "UUID")
  public UUID promptVersionId;

  @Column(nullable = false, length = 200)
  public String titulo;

  @Column(nullable = false, columnDefinition = "TEXT")
  public String enunciado;

  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "rubrica_oculta", nullable = false, columnDefinition = "jsonb")
  public JsonObject rubricaOculta;

  @Column(name = "contexto_origen", nullable = false, length = 30)
  public String contextoOrigen; // CORPORATIVO, ACADEMICO, BIBLIOTECA, ACADEMICO_INTEGRADOR

  @Column(nullable = false, length = 100)
  public String tecnologia;

  @Column(nullable = false, length = 20)
  public String seniority; // TRAINEE, JR, SSR, SR, LEAD

  @Column(name = "minutos_estimados", nullable = false)
  public Integer minutosEstimados = 60;

  @Column(name = "es_publico", nullable = false)
  public Boolean esPublico = false;

  @Column(name = "plan_evaluacion_id", columnDefinition = "UUID")
  public UUID planEvaluacionId;

  @Column(name = "tipo_desafio", length = 30)
  public String
      tipoDesafio; // TECNICO_PURO, TECNICO_CON_STACK, COMUNICACION, DOCUMENTACION, INTEGRACION

  @Column(precision = 5, scale = 2)
  public BigDecimal peso;

  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "cursos_integrados", columnDefinition = "jsonb")
  public JsonArray cursosIntegrados;

  @Column(nullable = false, length = 20)
  public String estado = "BORRADOR"; // BORRADOR, REVISION, ACTIVO, ARCHIVADO

  @Column(name = "created_at", nullable = false, updatable = false)
  public Instant createdAt;

  @Column(name = "updated_at", nullable = false)
  public Instant updatedAt;

  @PrePersist
  protected void onCreate() {
    if (id == null) {
      id = UUID.randomUUID();
    }
    createdAt = Instant.now();
    updatedAt = Instant.now();
  }

  @PreUpdate
  protected void onUpdate() {
    updatedAt = Instant.now();
  }

  public static Desafio findByIdOptional(UUID id) {
    return findById(id);
  }
}
